<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [6]:
%%sql

SELECT
  orderdate,
  quantity,
  netprice,
  CASE
    WHEN quantity >= 2 AND netprice >= 100 THEN 'Multiple High Value Order'
    WHEN netprice >= 100 THEN 'Single High Value Item'
    WHEN quantity >= 2 AND netprice < 100 THEN 'Multiple Standard Item'
    ELSE 'Single Standard Order' END AS order_type
FROM
  sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 order_type
0  2015-01-01         1     98.97      Single Standard Order
1  2015-01-01         1    659.78     Single High Value Item
2  2015-01-01         2     54.38     Multiple Standard Item
3  2015-01-01         4    286.69  Multiple High Value Order
4  2015-01-01         7    135.75  Multiple High Value Order
5  2015-01-01         3    434.30  Multiple High Value Order
6  2015-01-01         1     58.73      Single Standard Order
7  2015-01-01         3     74.99     Multiple Standard Item
8  2015-01-01         2    113.57  Multiple High Value Order
9  2015-01-01         1    499.45     Single High Value Item

In [14]:
%%sql

SELECT
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
FROM
  sales s
WHERE
  s.orderdate::date BETWEEN '2022-01-01' AND '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  398.00

In [78]:
%%sql

WITH median_value AS(
  SELECT
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
  FROM
    sales s
  WHERE
    s.orderdate::date BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname AS category,
  SUM( CASE WHEN (s.orderdate::date BETWEEN '2022-01-01' AND '2022-12-31') AND ((s.quantity * s.netprice * s.exchangerate) < mv.median) THEN (s.quantity * s.netprice * s.exchangerate)END) AS low_revenue_2022,
  SUM( CASE WHEN (s.orderdate::date BETWEEN '2022-01-01' AND '2022-12-31') AND ((s.quantity * s.netprice * s.exchangerate) >= mv.median) THEN (s.quantity * s.netprice * s.exchangerate)END) AS high_revenue_2022,
  SUM( CASE WHEN (s.orderdate::date BETWEEN '2023-01-01' AND '2023-12-31') AND ((s.quantity * s.netprice * s.exchangerate) < mv.median) THEN (s.quantity * s.netprice * s.exchangerate)END) AS low_revenue_2023,
  SUM( CASE WHEN (s.orderdate::date BETWEEN '2023-01-01' AND '2023-12-31') AND ((s.quantity * s.netprice * s.exchangerate) >= mv.median) THEN (s.quantity * s.netprice * s.exchangerate)END) AS high_revenue_2023
FROM
  sales s
CROSS JOIN
  median_value mv
LEFT JOIN
  product p ON p.productkey = s.productkey

GROUP BY
  category
ORDER BY
  category

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_revenue_2022,high_revenue_2022,low_revenue_2023,high_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87

from matplotlib import pyplot as plt
_df_0['low_revenue_2022'].plot(kind='hist', bins=20, title='low_revenue_2022')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['high_revenue_2022'].plot(kind='hist', bins=20, title='high_revenue_2022')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['low_revenue_2023'].plot(kind='hist', bins=20, title='low_revenue_2023')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['high_revenue_2023'].plot(kind='hist', bins=20, title='high_revenue_2023')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('category').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='low_revenue_2022', y='high_revenue_2022', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='high_revenue_2022', y='low_revenue_2023', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='low_revenue_2023', y='high_revenue_2023', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8['low_revenue_2022'].plot(kind='line', figsize=(8, 4), title='low_revenue_2022')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['high_revenue_2022'].plot(kind='line', figsize=(8, 4), title='high_revenue_2022')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['low_revenue_2023'].plot(kind='line', figsize=(8, 4), title='low_revenue_2023')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11['high_revenue_2023'].plot(kind='line', figsize=(8, 4), title='high_revenue_2023')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_12['category'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_12, x='low_revenue_2022', y='category', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_13['category'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_13, x='high_revenue_2022', y='category', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_14['category'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_14, x='low_revenue_2023', y='category', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_15['category'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_15, x='high_revenue_2023', y='category', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)